### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by Donnie** [openjustice-in/ecourts#25]
https://github.com/captn3m0/ecourts/blob/1db17a98d9400561a142616c02e2d8ec2e5c3eaa/src/cli/__init__.py#L188

It seems these functions are missing. Are they supposed to load from some library, or are they placeholders and you need contribution in implementing them?

**Comment by captn3m0** [comment]
I decided against implementing them. I realised that using a "Case" as the base layer makes more sense, since scraping only for Orders is very haphazard. It's better to start with cases, then enrich them, and then fetch the Orders for the appropriate Cases where needed.

Even for "single fetch" use cases (not a bulk scrape), it is always better to start with a Case.

**Comment by captn3m0** [comment]
https://github.com/captn3m0/ecourts/issues/6 covers it a bit more. I'll be dropping the order-first interface in the next few releases.
